### ISSUE TITLE
TypeError: unicodeText must be unicode

### ISSUE THREAD

**Issue by LionelR** [hlamer/qutepart#27]
Can't use Qutepart on Ubuntu 14.04 with python2.7 and PyQt 4.10.4 with the following code: 
```python
from qutepart import Qutepart


class QueryEditor(Qutepart):
    def __init__(self, *args, **kwargs):
        super(QueryEditor, self).__init__(*args, **kwargs)
        self.completionEnabled = True
        self.completionThreshold = 2
        self.indentUseTabs = True
        self.indentWidth = 4
        self.detectSyntax(xmlFileName="sql-postgresql.xml")

    def setText(self, text):
        self.text = text

    def getText(self):
        return self.text


if __name__ == "__main__":
    from PyQt4 import QtGui
    import sys
    app = QtGui.QApplication(sys.argv)
    editor = QueryEditor()
    editor.show()
    editor.setText(open(sys.argv[0]).read())
    app.exec_()
```

and the traceback :
```
Traceback (most recent call last):
  File "/home/lionel/Developpement/Projets/pgleon/ui/widgets/editor.py", line 29, in <module>
    editor = QueryEditor()
  File "/home/lionel/Developpement/Projets/pgleon/ui/widgets/editor.py", line 16, in __init__
    self.detectSyntax(xmlFileName="sql-postgresql.xml")
  File "/usr/local/lib/python2.7/dist-packages/qutepart/__init__.py", line 674, in detectSyntax
    self._highlighter = SyntaxHighlighter(syntax, self)
  File "/usr/local/lib/python2.7/dist-packages/qutepart/syntaxhlighter.py", line 114, in __init__
    self._onContentsChange(0, 0, charsAdded, zeroTimeout=self._wasChangedJustBefore())
  File "/usr/local/lib/python2.7/dist-packages/qutepart/syntaxhlighter.py", line 220, in _onContentsChange
    self._highlighBlocks(firstBlock, untilBlock, timeout)
  File "/usr/local/lib/python2.7/dist-packages/qutepart/syntaxhlighter.py", line 242, in _highlighBlocks
    lineData, highlightedSegments = self._syntax.highlightBlock(block.text(), contextStack)
TypeError: unicodeText must be unicode
```

**Comment by hlamer** [comment]
You are using QString API v1. Use v2. 
Insert next code

```python
import sip
sip.setapi('QString', 2)
```

before importing Qutepart.

I've added a check up to Qutepart. Now it will raise an exception with explanation what is wrong if QString API v2 is not set.
