### ISSUE TITLE
AttributeError: type object 'QApplication' has no attribute 'instance'

### ISSUE THREAD

**Issue by rapgro** [hlamer/qutepart#29]
```
+ make html
sphinx-build -b html -d build/doctrees   source build/html
Making output directory...
Running Sphinx v1.2.3

Exception occurred:
  File "/home/builder/rpmbuild/BUILD/qutepart-2.2.2/qutepart/syntaxhlighter.py", line 53, in __init__
    self._timer = QTimer(QApplication.instance())
AttributeError: type object 'QApplication' has no attribute 'instance'
The full traceback has been saved in /tmp/sphinx-err-dLBlPs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```
See also: https://www.readthedocs.org/projects/qutepart/builds/2506996/

**Comment by rapgro** [comment]
```
> cat /tmp/sphinx-err-dLBlPs.log
# Sphinx version: 1.2.3
# Python version: 2.7.10
# Docutils version: 0.12 repository
# Jinja2 version: 2.8
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 53, in <module>
  File "/home/builder/rpmbuild/BUILD/qutepart-2.2.2/qutepart/__init__.py", line 27, in <module>
    from qutepart.syntaxhlighter import SyntaxHighlighter
  File "/home/builder/rpmbuild/BUILD/qutepart-2.2.2/qutepart/syntaxhlighter.py", line 91, in <module>
    class SyntaxHighlighter(QObject):
  File "/home/builder/rpmbuild/BUILD/qutepart-2.2.2/qutepart/syntaxhlighter.py", line 98, in SyntaxHighlighter
    _globalTimer = GlobalTimer()
  File "/home/builder/rpmbuild/BUILD/qutepart-2.2.2/qutepart/syntaxhlighter.py", line 53, in __init__
    self._timer = QTimer(QApplication.instance())
AttributeError: type object 'QApplication' has no attribute 'instance'
```

**Comment by hlamer** [comment]
Check current `master`. I should build fine.

@rapgro, for which project are you building Qutepart?
Have you seen http://software.opensuse.org/download.html?project=home%3Ahlamer%3Aenki&package=python-qutepart

**Comment by rapgro** [comment]
I take over from Yajo to introduce official packages in Fedora, see #3 and hlamer/enki#124.
Package review: https://bugzilla.redhat.com/show_bug.cgi?id=1015868

**Comment by hlamer** [comment]
Cool!
